#!/usr/bin/env node
/**
 * Build-time data pipeline: parse the FreeDict Latin–German dictionary (TEI)
 * into a large bundled vocabulary dataset.
 *
 * SOURCE (Latin→German, ~5500 entries, GPL):
 *   https://github.com/freedict/fd-dictionaries  → lat-deu/lat-deu.tei
 *   Download once to: scripts/sources/lat-deu.tei
 *     curl -fsSL https://raw.githubusercontent.com/freedict/fd-dictionaries/master/lat-deu/lat-deu.tei \
 *       -o scripts/sources/lat-deu.tei
 *
 * OUTPUT: src/data/vocab.generated.ts  (merged with the curated core in vocab.ts)
 *
 * The curated 50 high-frequency words (src/data/vocab.ts) stay as portions 1–6;
 * FreeDict entries are de-duplicated against them and appended.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const TEI = join(__dirname, 'sources', 'lat-deu.tei');
const CORE = join(ROOT, 'src', 'data', 'vocab.ts');
const OUT = join(ROOT, 'src', 'data', 'vocab.generated.ts');

if (!existsSync(TEI)) {
  console.error(
    `\n⚠  Quelle fehlt: ${TEI}\n` +
      `   curl -fsSL https://raw.githubusercontent.com/freedict/fd-dictionaries/master/lat-deu/lat-deu.tei \\\n` +
      `     -o scripts/sources/lat-deu.tei\n` +
      `   Danach erneut: npm run seed\n`,
  );
  process.exit(1);
}

const decodeEntities = (s) =>
  s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(parseInt(d, 10)))
    .trim();

// Mirror src/lib/latin/normalize.ts so dedup keys match the app.
const normalize = (w) =>
  w
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '') // strip combining diacritics (macrons)
    .replace(/[^a-zü]/g, '')
    .replace(/v/g, 'u')
    .replace(/j/g, 'i');

const POS_MAP = {
  n: 'noun', noun: 'noun', subst: 'noun',
  v: 'verb', verb: 'verb',
  adj: 'adj', adjective: 'adj',
  adv: 'adv', adverb: 'adv',
  prep: 'prep', praep: 'prep', preposition: 'prep',
  conj: 'conj', conjunction: 'conj',
  pron: 'pron', pronoun: 'pron',
  num: 'num', numeral: 'num',
  interj: 'interj', int: 'interj',
};

const tei = readFileSync(TEI, 'utf8');

// Core headwords to exclude (curated set wins).
const coreText = readFileSync(CORE, 'utf8');
const coreKeys = new Set([...coreText.matchAll(/lemma:\s*'([^']+)'/g)].map((m) => normalize(m[1])));

const matchAll = (re, s) => [...s.matchAll(re)].map((m) => m[1]);

const entries = [...tei.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/g)].map((m) => m[1]);

const merged = new Map(); // key -> {headword, pos, glosses:Set, forms:Set}

for (const block of entries) {
  const orths = matchAll(/<orth\b[^>]*>([\s\S]*?)<\/orth>/g, block).map(decodeEntities).filter(Boolean);
  if (orths.length === 0) continue;
  const headword = orths[0];
  const key = normalize(headword);
  if (!key || coreKeys.has(key)) continue;

  const posRaw = (block.match(/<pos\b[^>]*>([\s\S]*?)<\/pos>/) ?? [])[1];
  const pos = POS_MAP[(posRaw ? decodeEntities(posRaw).toLowerCase() : '').replace(/\.$/, '')] ?? 'other';

  // German translations: <cit type="trans"> … <quote>…</quote>
  const transBlocks = matchAll(/<cit\b[^>]*type="trans"[^>]*>([\s\S]*?)<\/cit>/g, block);
  const glosses = [];
  for (const tb of transBlocks) {
    for (const q of matchAll(/<quote\b[^>]*>([\s\S]*?)<\/quote>/g, tb)) {
      const g = decodeEntities(q.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' '));
      if (g) glosses.push(g);
    }
  }
  if (glosses.length === 0) continue;

  const existing = merged.get(key);
  if (existing) {
    glosses.forEach((g) => existing.glosses.add(g));
    orths.forEach((o) => existing.forms.add(o.toLowerCase()));
  } else {
    merged.set(key, {
      headword,
      pos,
      glosses: new Set(glosses),
      forms: new Set(orths.map((o) => o.toLowerCase())),
    });
  }
}

// Order: shorter headwords first (rough proxy for more basic), then alpha.
const list = [...merged.values()].sort(
  (a, b) => a.headword.length - b.headword.length || a.headword.localeCompare(b.headword),
);

const GROUP_SIZE = 100;
const BASE_ID = 1000; // curated core uses 1..50
const lemmas = list.map((e, i) => ({
  id: BASE_ID + i,
  lemma: e.headword,
  pos: e.pos,
  glossDe: [...e.glosses].slice(0, 3).join('; ').slice(0, 140),
  freqRank: 1000 + i,
  freqGroup: 7 + Math.floor(i / GROUP_SIZE),
  forms: [...e.forms].slice(0, 12),
}));

const body =
  `// AUTO-GENERATED by scripts/build-seed.mjs — do not edit by hand.\n` +
  `// Source: FreeDict lat-deu (Latin–German), GPL. ${lemmas.length} entries.\n` +
  `import type { SeedLemma } from './types';\n\n` +
  `export const GENERATED_VOCAB: SeedLemma[] = ${JSON.stringify(lemmas)};\n`;
writeFileSync(OUT, body, 'utf8');
console.log(`✓ ${lemmas.length} Lemmas (von ${entries.length} TEI-Einträgen) → ${OUT}`);
