// Auto-generated by scripts/build-seed-ja.mjs (JMdict + JLPT/frequency).
// Placeholder until the generator has been run; see scripts/build-seed-ja.mjs.
import type { SeedLemma } from './types';

export const GENERATED_VOCAB_JA: SeedLemma[] = [];
